accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 25
benchmark: false
bidirectional: true
check_val_every_n_epoch: 1
checkpoint_callback: null
data_pct: 1.0
default_root_dir: null
detect_anomaly: false
deterministic: true
devices: null
emb_dim: 128
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
epsilon: 0.05
experiment_name: ''
fast_dev_run: false
flush_logs_every_n_steps: null
freeze_bert: false
freeze_prototypes_epochs: 1
gpus: 1
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_dim: 768
img_encoder: vit_base
ipus: null
lamb: 0.75
lambda_0: 3
lambda_1: 0
lambda_2: 1.0
lambda_3: 0.5
learning_rate: 2.0e-05
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
local_temperature: 0.1
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 50
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
momentum: 0.9
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_heads: 1
num_nodes: 1
num_processes: 1
num_prototypes: 500
num_sanity_val_steps: 2
num_workers: 0
overfit_batches: 0.0
plugins: null
precision: 16
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
proto_temperature: 0.2
query_num: 32
queue_size: 100
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 42
sinkhorn_iterations: 3
softmax_temperature: 0.07
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
use_local_atten: false
val_check_interval: 1.0
weight_decay: 0.05
weights_save_path: null
weights_summary: top
